# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/mybatis-test?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root


# Logger Config
logging:
  level:
    cn.bobz.myspcmybatis: debug
# MyBatis-Plus 配置该演示无